development:
  secret_key_base: 7fbefe60a3ccb7db719615eb3c3079e9204b1fda8256c77da18348bd8b810d6a8db4683985c4483e48ea94560fd0258c33980ca2e96c01fe6662e07fdbaa8ec6
  domain_name: localhost

test:
  secret_key_base: 8f17ca9468a7b27ee7d24f98a3934143913ef12c411eef7c920a018a6816d2f41a412caa187767bc3ad30168a45e6a46a88ca4ba4c32811df4852c0000fdbc9b
  domain_name: localhost

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: localhost
